export const ADD_CHILD_SUCCESS = "ADD_CHILD_SUCCESS"
export const GET_FAMILY_SUCCESS = "GET_FAMILY_SUCCESS"
export const SELECT_CHILD = "SELECT_CHILD"
export const EDIT_CHILD_SUCCESS = "EDIT_CHILD_SUCCESS"